### ISSUE TITLE
Changing the save function to catch errors

### ISSUE THREAD

**Issue by neilong31** [agarcia-caicedo/tinyNote#5]
You can change your save() and saveAlert() functions to one function called saveFile(). Also, check if the function throws an error and try and catch it.

Ex.

```
function saveFile() {
    fs.writeFile('/note', document.querySelector('#note').innerHTML, function(err) {
        if(err) {
            console.error('Error saving', err);
            return alert('Unable to Save!');
        }
        return alert('Saved!');
    });
}
```

**Comment by neilong31** [comment]
550decd84d5af04a6aa8abccfc1d06653add1e48

**Comment by a-ciacaicedo** [comment]
Thanks for noticing the error and fixing it

**Comment by a-ciacaicedo** [comment]
66dd68536c07b87f706914eb4e141aa0433ba16c
